from PyQt5.QtWidgets import QComboBox, QMainWindow, QApplication, QWidget, QVBoxLayout, QPushButton 
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot
import sys


class MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()

        self.setWindowTitle('APT/Attack Vector Search')

        combobox1 = QComboBox()
        combobox1.addItem('Reconnaissance')
        combobox1.addItem('Active Scanning')
        combobox1.addItem('Gather Victim Host Information')
        combobox1.addItem('Gather Victim Identity Information')
        combobox1.addItem('Gather Victim Network Information')
        combobox1.addItem('Gather Victim Org Information')
        combobox1.addItem('Phishing for Information')
        combobox1.addItem('Search Closed Sources')
        combobox1.addItem('Search Open Technical Databases')
        combobox1.addItem('Search Open Websites/Domains')
        combobox1.addItem('Search Victim-Owned Websites')
        

        combobox2 = QComboBox()
        combobox2.addItem('Resource Development')
        combobox2.addItem('Acquire Infrastructure')
        combobox2.addItem('Compromise Accounts')
        combobox2.addItem('Compromise Infrastructure')
        combobox2.addItem('Develop Capabilities')
        combobox2.addItem('Establish Accounts')
        combobox2.addItem('Obtain Capabilities')
        combobox2.addItem('Stage Capabilities')

        combobox3 = QComboBox()
        combobox3.addItem('Initial Access')
        combobox3.addItem('Drive-by Compromise')
        combobox3.addItem('Exploit Public-Facing Application')
        combobox3.addItem('External Remote Services')
        combobox3.addItem('Hardware Additions')
        combobox3.addItem('Phishing')
        combobox3.addItem('Replication Through Removable Media')
        combobox3.addItem('Supply Chain Compromise')
        combobox3.addItem('Trusted Relationship')
        combobox3.addItem('Valid Accounts')
        

        combobox4 = QComboBox()
        combobox4.addItem('Execution')
        combobox4.addItem('Command and Scripting Interpreter')
        combobox4.addItem('Container Administration Command')
        combobox4.addItem('Deploy Container')
        combobox4.addItem('Exploitation for Client Execution')
        combobox4.addItem('Inter-Process Communication')
        combobox4.addItem('Native API')
        combobox4.addItem('Scheduled Task/Job')
        combobox4.addItem('Shared Modules')
        combobox4.addItem('Software Deployment Tools')
        combobox4.addItem('System Services')
        combobox4.addItem('User Execution')
        combobox4.addItem('Windows Management Instrumentation')

        combobox5 = QComboBox()
        combobox5.addItem('Persistence')
        combobox5.addItem('Account Manipulation')
        combobox5.addItem('BITS Jobs')
        combobox5.addItem('Boot or Logon Autostart Execution')
        combobox5.addItem('Boot or Logon Initialization Scripts')
        combobox5.addItem('Browser Extensions')
        combobox5.addItem('Compromise Client Software Binary')
        combobox5.addItem('Create Account')
        combobox5.addItem('Create or Modify System Process')
        combobox5.addItem('Event Triggered Execution')
        combobox5.addItem('External Remote Services')
        combobox5.addItem('Hijack Execution Flow')
        combobox5.addItem('Implant Internal Image')
        combobox5.addItem('Modify Authentication Process')
        combobox5.addItem('Office Application Startup')
        combobox5.addItem('Pre-OS Boot')
        combobox5.addItem('Scheduled Task/Job')
        combobox5.addItem('Server Software Component')
        combobox5.addItem('Traffic Signaling')
        combobox5.addItem('Valid Accounts')

        combobox6 = QComboBox()
        combobox6.addItem('Privilege Escalation')
        combobox6.addItem('Abuse Elevation Control Mechanism')
        combobox6.addItem('Access Token Manipulation')
        combobox6.addItem('Boot or Logon Autostart Execution')
        combobox6.addItem('Boot or Logon Initialization Scripts')
        combobox6.addItem('Create or Modify System Process')
        combobox6.addItem('Domain Policy Modification')
        combobox6.addItem('Escape to Host')
        combobox6.addItem('Event Triggered Execution')
        combobox6.addItem('Exploitation for Privilege Escalation')
        combobox6.addItem('Hijack Execution Flow')
        combobox6.addItem('Process Injection')
        combobox6.addItem('Scheduled Task/Job')
        combobox6.addItem('Valid Accounts')
        

        combobox7 = QComboBox()
        combobox7.addItem('Defence Evasion')
        combobox7.addItem('Abuse Elevation Control Mechanism')
        combobox7.addItem('Access Token Manipulation')
        combobox7.addItem('BITS Jobs')
        combobox7.addItem('Build Image on Host')
        combobox7.addItem('Deobfuscate/Decode Files or Information')
        combobox7.addItem('Deploy Container')
        combobox7.addItem('Direct Volume Access')
        combobox7.addItem('Domain Policy Modification')
        combobox7.addItem('Execution Guardrails')
        combobox7.addItem('Exploitation for Defense Evasion')
        combobox7.addItem('File and Directory Permissions Modification')
        combobox7.addItem('Hide Artifacts')
        combobox7.addItem('Hijack Execution Flow')
        combobox7.addItem('Impair Defenses')
        combobox7.addItem('Indicator Removal on Host')
        combobox7.addItem('Indirect Command Execution')
        combobox7.addItem('Masquerading')
        combobox7.addItem('Modify Authentication Process')
        combobox7.addItem('Modify Cloud Compute Infrastructure')
        combobox7.addItem('Modify Registry')
        combobox7.addItem('Modify System Image')
        combobox7.addItem('Network Boundary Bridging')
        combobox7.addItem('Obfuscated Files or Information')
        combobox7.addItem('Pre-OS Boot')
        combobox7.addItem('Process Injection')
        combobox7.addItem('Reflective Code Loading')
        combobox7.addItem('Rogue Domain Controller')
        combobox7.addItem('Rootkit')
        combobox7.addItem('Signed Binary Proxy Execution')
        combobox7.addItem('Signed Script Proxy Execution')
        combobox7.addItem('Subvert Trust Controls')
        combobox7.addItem('Template Injection')
        combobox7.addItem('Traffic Signaling')
        combobox7.addItem('Trusted Developer Utilities Proxy Execution')
        combobox7.addItem('Unused/Unsupported Cloud Regions')
        combobox7.addItem('Use Alternate Authentication Material')
        combobox7.addItem('Valid Accounts')
        combobox7.addItem('Virtualization/Sandbox Evasion')
        combobox7.addItem('Weaken Encryption')
        combobox7.addItem('XSL Script Processing')

        

        combobox8 = QComboBox()
        combobox8.addItem('Credential Access')
        combobox8.addItem('Adversary-in-the-Middle')
        combobox8.addItem('Brute Force')
        combobox8.addItem('Credentials from Password Stores')
        combobox8.addItem('Exploitation for Credential Access')
        combobox8.addItem('Forced Authentication')
        combobox8.addItem('Forge Web Credentials')
        combobox8.addItem('Input Capture')
        combobox8.addItem('Modify Authentication Process')
        combobox8.addItem('Network Sniffing')
        combobox8.addItem('OS Credential Dumping')
        combobox8.addItem('Steal Application Access Token')
        combobox8.addItem('Steal or Forge Kerberos Tickets')
        combobox8.addItem('Steal Web Session Cookie')
        combobox8.addItem('Two-Factor Authentication Interception')
        combobox8.addItem('Unsecured Credentials')
        

        combobox9 = QComboBox()
        combobox9.addItem('Discovery')
        combobox9.addItem('Account Discovery')
        combobox9.addItem('Application Window Discovery')
        combobox9.addItem('Browser Bookmark Discovery')
        combobox9.addItem('Cloud Infrastructure Discovery')
        combobox9.addItem('Cloud Service Dashboard')
        combobox9.addItem('Cloud Service Discovery')
        combobox9.addItem('Cloud Storage Object Discovery')
        combobox9.addItem('Container and Resource Discovery')
        combobox9.addItem('Domain Trust Discovery')
        combobox9.addItem('File and Directory Discovery')
        combobox9.addItem('Group Policy Discovery')
        combobox9.addItem('Network Service Scanning')
        combobox9.addItem('Network Share Discovery')
        combobox9.addItem('Network Sniffing')
        combobox9.addItem('Password Policy Discovery')
        combobox9.addItem('Peripheral Device Discovery')
        combobox9.addItem('Permission Groups Discovery')
        combobox9.addItem('Process Discovery')
        combobox9.addItem('Query Registry')
        combobox9.addItem('Remote System Discovery')
        combobox9.addItem('Software Discovery')
        combobox9.addItem('System Information Discovery')
        combobox9.addItem('System Location Discovery')
        combobox9.addItem('System Network Configuration Discovery')
        combobox9.addItem('System Network Connections Discovery')
        combobox9.addItem('System Owner/User Discovery')
        combobox9.addItem('System Service Discovery')
        combobox9.addItem('System Time Discovery')
        combobox9.addItem('Virtualization/Sandbox Evasion')
        

        combobox10 = QComboBox()
        combobox10.addItem('Lateral Movement')
        combobox10.addItem('Exploitation of Remote Services')
        combobox10.addItem('Internal Spearphishing')
        combobox10.addItem('Lateral Tool Transfer')
        combobox10.addItem('Remote Service Session Hijacking')
        combobox10.addItem('Remote Services')
        combobox10.addItem('Replication Through Removable Media')
        combobox10.addItem('Software Deployment Tools')
        combobox10.addItem('Taint Shared Content')
        combobox10.addItem('Use Alternate Authentication Material')
        

        combobox11 = QComboBox()
        combobox11.addItem('Collection')
        combobox11.addItem('Adversary-in-the-Middle')
        combobox11.addItem('Archive Collected Data')
        combobox11.addItem('Audio Capture')
        combobox11.addItem('Automated Collection')
        combobox11.addItem('Browser Session Hijacking')
        combobox11.addItem('Clipboard Data')
        combobox11.addItem('Data from Cloud Storage Object')
        combobox11.addItem('Data from Configuration Repository')
        combobox11.addItem('Data from Information Repositories')
        combobox11.addItem('Data from Local System')
        combobox11.addItem('Data from Network Shared Drive')
        combobox11.addItem('Data from Removable Media')
        combobox11.addItem('Data Staged')
        combobox11.addItem('Email Collection')
        combobox11.addItem('Input Capture')
        combobox11.addItem('Screen Capture')
        combobox11.addItem('Video Capture')
        

        combobox12 = QComboBox()
        combobox12.addItem('Command and Control')
        combobox12.addItem('Application Layer Protocol')
        combobox12.addItem('Communication Through Removable Media')
        combobox12.addItem('Data Encoding')
        combobox12.addItem('Data Obfuscation')
        combobox12.addItem('Dynamic Resolution')
        combobox12.addItem('Encrypted Channel')
        combobox12.addItem('Fallback Channels')
        combobox12.addItem('Ingress Tool Transfer')
        combobox12.addItem('Multi-Stage Channels')
        combobox12.addItem('Non-Application Layer Protocol')
        combobox12.addItem('Non-Standard Port')
        combobox12.addItem('Protocol Tunneling')
        combobox12.addItem('Proxy')
        combobox12.addItem('Remote Access Software')
        combobox12.addItem('Traffic Signaling')
        combobox12.addItem('Web Service')

        combobox13 = QComboBox()
        combobox13.addItem('Exfiltration')
        combobox13.addItem('Automated Exfiltration')
        combobox13.addItem('Data Transfer Size Limits')
        combobox13.addItem('Exfiltration Over Alternative Protocol')
        combobox13.addItem('Exfiltration Over C2 Channel')
        combobox13.addItem('Exfiltration Over Other Network Medium')
        combobox13.addItem('Exfiltration Over Physical Medium')
        combobox13.addItem('Exfiltration Over Web Service')
        combobox13.addItem('Scheduled Transfer')
        combobox13.addItem('Transfer Data to Cloud Account')
        

        combobox14 = QComboBox()
        combobox14.addItem('Impact')
        combobox14.addItem('Account Access Removal')
        combobox14.addItem('Data Destruction')
        combobox14.addItem('Data Encrypted for Impact')
        combobox14.addItem('Data Manipulation')
        combobox14.addItem('Defacement')
        combobox14.addItem('Disk Wipe')
        combobox14.addItem('Endpoint Denial of Service')
        combobox14.addItem('Firmware Corruption')
        combobox14.addItem('Inhibit System Recovery')
        combobox14.addItem('Network Denial of Service')
        combobox14.addItem('Resource Hijacking')
        combobox14.addItem('Service Stop')
        combobox14.addItem('System Shutdown/Reboot')

        button1 = QPushButton()
        button1.setText("Search")
        
        
        layout = QVBoxLayout()
        layout.addWidget(combobox1)
        layout.addWidget(combobox2)
        layout.addWidget(combobox3)
        layout.addWidget(combobox4)
        layout.addWidget(combobox5)
        layout.addWidget(combobox6)
        layout.addWidget(combobox7)
        layout.addWidget(combobox8)
        layout.addWidget(combobox9)
        layout.addWidget(combobox10)
        layout.addWidget(combobox11)
        layout.addWidget(combobox12)
        layout.addWidget(combobox13)
        layout.addWidget(combobox14)
        layout.addWidget(button1)

        container = QWidget()
        container.setLayout(layout)

        self.setCentralWidget(container)

    def current_text_changed(self, s):
        print("Current text: ", s)
    
    


app = QApplication(sys.argv)
w = MainWindow()
w.show()
app.exec_()
